### ISSUE TITLE
Update to Remix v2

### ISSUE THREAD

**Issue by UncleGravity** [sjc5/remix-easy-mode#13]
Remix v2 is finally out and I'd love to continue using this! Awesome library btw.

**Comment by sjc5** [comment]
Hey @UncleGravity, thanks!

You're right, I'll upgrade this very soon when I get some time.

Thanks for the bump!

**Comment by sjc5** [comment]
Given how stable and incremental the Remix v2 launch was, we can probably simply change the `^` to `>=` in package.json. I'll try to test tonight after work and get a new release out.

**Comment by UncleGravity** [comment]
I installed it with `npm install --legacy-peer-deps remix-easy-mode` and it's working without issues, so you're probably right.

**Comment by sjc5** [comment]
Hey there @UncleGravity, thanks for your patience. Just released v0.2.1 which should be compatible with the latest version of Remix now. There was some goofiness with the new version of useFetcher that dropped in Remix v2.2.0, but it should be working now. Let me know if you run into any issues. Thanks!

Release: https://github.com/sjc5/remix-easy-mode/releases/tag/v0.2.1

**Comment by UncleGravity** [comment]
Awesome @sjc5 , just upgraded everything and it works without a problem 👍

**Comment by sjc5** [comment]
Awesome thanks much @UncleGravity -- make sure to bump up to v0.2.2 as well if you didn't already, fixes a little issue I found in v0.2.1 related to the new Remix fetcher keys
