### ISSUE TITLE
Is this project still current or there's a new way of doing things with the current remix version?

### ISSUE THREAD

**Issue by muchisx** [sjc5/remix-easy-mode#17]
Currently looking for a solution for typed front-end to back-end operations and stumpled uppon this

**Comment by sjc5** [comment]
Hey there @muchisx, indeed this is still current and as far as I know the closest thing to TRPC in Remix-land. Let me know if you hit any snags.

**Comment by muchisx** [comment]
Thank you @sjc5, I'll give it a try!
Let me know if you make a new video with this updated version, I see the video you made was with your first iteration of it!
